# -*- coding: utf-8 -*-
"""
Created on Thu Dec 28 19:42:59 2023

@author: Steven
"""

import random

def pick_words(jp, number_of):
    if number_of > len(jp):
        print("Error, Number to pick is greater than the length of the list")
        return None

    selected_words = random.sample(jp, number_of)
    return selected_words

jp = ["それ - that, that one",
"一つ	 - ひとつ - one (thing)",
"一 - いち - one",
"二 - に - two",
"二つ - ふたつ - two (things)",
"三 - さん - three",
"三つ - みっつ - three (things)",
"四つ - よっつ - four (things)",
"四 - し - four",
"これ - this, this one",
"五つ - いつつ - five (things)",
"五 - ご - five",
"六つ - むっつ - six (things)",
"六 - ろく - six",
"七つ - ななつ - seven (things)",
"八 - はち - eight",
"八つ - やっつ - eight (things)",
"なる - become",
"九 - きゅう - nine",
"九つ - ここのつ - nine (things)",
"十 - じゅう - ten",
"百 - ひゃく - hundred",
"千 - せん - thousand",
"万 - まん - ten thousand",
"する - do, make",
"時々 - ときどき - sometimes",
"六日 - むいか - six days, 6th of the month",
"三日 - みっか - three days, 3rd of the month",
"五日 - いつか - five days, 5th of the month",
"八日 - ようか - eight days, 8th of the month",
"二十日 - はつか - 20 days, 20th of the month",
"二日 - ふつか - two days, 2nd of the month",
"九日 - ここのか - nine days, 9th of the month",
"一日 - ついたち - 1st of the month",
"十日 - とおか - ten days, 10th of the month",
"七日 - なのか - seven days, 7th of the month",
"四日 - よっか - four days, 4th of the month",
"水 - みず - water",
"日曜日 - にちようび - Sunday",
"土曜日 - どようび - Saturday",
"やる - do",
"金曜日 - きんようび - Friday",
"月曜日 - げつようび - Monday",
"木曜日 - もくようび - Thursday",
"火曜日 - かようび - Tuesday",
"水曜日 - すいようび - Wednesday",
"そう - in such manner, that way",
"何 - なに - what, which",
"先 - さき - ahead, first",
"今年 - ことし - this year",
"今 - いま - now",
"今日 - きょう - today",
"今月 - こんげつ - this month",
"今週 - こんしゅう - this week",
"来る - くる - come",
"来年 - らいねん - next year",
"もう - already, yet",
"行く - いく - go",
"帰る - かえる - return, go back",
"大きい - おおきい - big",
"小さい - ちいさい - small",
"少し - すこし - a bit, a little while",
"上げる - あげる - raise, improve",
"よく - often",
"上 - うえ - up, above",
"下 - した - under, below",
"右 - みぎ - right",
"左 - ひだり - left",
"大人 - おとな - adult",
"人 - ひと - person",
"一人 - ひとり - one, one person",
"どう - how, what",
"入れる - いれる - put in",
"入る - はいる - enter",
"出る - でる - go out, leave",
"出す - だす - take out",
"本 - ほん - book, volume",
"休む - やすむ - take a day off, take a break",
"体 - からだ - body, health",
"目 - め - eye",
"どこ - where",
"口 - くち - mouth",
"耳 - みみ - ear, hearing",
"上手 - じょうず - good, skilled",
"手 - て - hand",
"足 - あし - leg, foot",
"男 - おとこ - man, male",
"女 - おんな - woman, girl",
"子供 - こども - child, kid",
"好き - すき - favorite, liked",
"大好き - だいすき - love",
"友達 - ともだち - friend, companion",
"元気 - げんき - healthy, energetic",
"天気 - てんき - weather",
"晴れる - はれる - be sunny, clear up",
"昨日 - きのう - yesterday",
"開ける - あける - open, unlock",
"閉める - しめる - shut, close",
"閉まる - しまる - be shut, be closed",
"聞く - きく - hear, ask",
"時間 - じかん - time, hour",
"高い - たかい - high, tall",
"安い - やすい - inexpensive, cheap",
"低い - ひくい - low, short",
"前 - まえ - front, before",
"後 - あと - after",
"午後 - ごご - afternoon, p.m.",
"午前 - ごぜん - morning, a.m.",
"朝 - あさ - morning",
"昼 - ひる - daytime, midday",
"晩 - ばん - evening (usually from sunset to bedtime)",
"今晩 - こんばん - this evening, tonight",
"夜 - よる - night (from sunset to sunrise)",
"食べる - たべる - eat",
"飲む - のむ - drink",
"買う - かう - buy",
"見る - みる - see, look at",
"見せる - みせる - show",
"もっと - more",
"言う - いう - say, tell",
"話す - はなす - speak, tell",
"読む - よむ - read",
"漢字 - かんじ - character, kanji",
"書く - かく - write",
"覚える - おぼえる - memorize, learn",
"そこ - there",
"会う - あう - meet",
"仕事 - しごと - work, job",
"車 - くるま - car, automobile",
"電車 - でんしゃ - train",
"駅 - えき - railway station",
"道 - みち - road, street",
"ここ - here",
"歩く - あるく - walk, go on foot",
"走る - はしる - run",
"近く - ちかく - near, close to",
"近い - ちかい - near, soon",
"近く - ちかく - vicinity, nearby",
"遠い - とおい - far, distant",
"長い - ながい - long",
"短い - みじかい - short, brief",
"広い - ひろい - wide, big",
"全部 - ぜんぶ - all, wholly",
"国 - くに - country",
"白い - しろい - white, blank",
"赤い - あかい - red",
"部屋 - へや - room",
"とても - very",
"作る - つくる - make, create",
"使う - つかう - use",
"消す - けす - switch off, turn off",
"売る - うる - sell",
"店 - みせ - shop, store",
"春 - はる - spring",
"夏 - なつ - summer",
"秋 - あき - autumn, fall",
"冬 - ふゆ - winter",
"みんな - all, everybody",
"暑い - あつい - hot, warm (temperature of the air)",
"熱い - あつい - hot (things, touch)",
"寒い - さむい - cold (temperature of the air)",
"暖かい - あたたかい - warm",
"新しい - あたらしい - new",
"古い - ふるい - old",
"悪い - わるい - bad",
"いつも - always",
"忘れる - わすれる - forget, leave behind",
"知る - しる - know",
"住む - すむ - live, reside",
"名前 - なまえ - name",
"食べ物 - たべもの - food",
"いつ - when",
"飲み物 - のみもの - beverage, drink",
"重い - おもい - heavy",
"軽い - かるい - light, light weight",
"取る - とる - take, get",
"待つ - まつ - wait, wait for",
"持つ - もつ - have, possess",
"どちら - which",
"先生 - せんせい - teacher",
"大学 - だいがく - university, college",
"学生 - がくせい - student",
"学校 - がっこう - school",
"教える - おしえる - teach, tell",
"勉強 - べんきょう - study",
"強い - つよい - strong",
"どれ - what, which",
"引く - ひく - draw, pull",
"質問 - しつもん - question",
"難しい - むずかしい - difficult",
"要る - いる - need, require",
"ドア - door",
"時計 - とけい - clock, watch",
"切る - きる - cut",
"乗る - のる - ride, take",
"着る - きる - wear, put on",
"立つ - たつ - stand, rise",
"座る - すわる - sit, sit down",
"次 - つぎ - next",
"働く - はたらく - work",
"早い - はやい - early",
"速い - はやい - fast",
"遅い - おそい - slow, late",
"始まる - はじまる - begin",
"テーブル - table",
"去年 - きょねん - last year",
"紙 - かみ - paper",
"楽しい - たのしい - fun, enjoyable",
"歌う - うたう - sing",
"欲しい - ほしい - want, desire",
"色 - いろ - color",
"茶色 - ちゃいろ - light brown",
"同じ - おなじ - same, identical",
"違う - ちがう - differ, be wrong",
"図書館 - としょかん - library",
"遊ぶ - あそぶ - play",
"どうして - why",
"服 - ふく - clothes",
"お父さん - おとうさん - father",
"父 - ちち - (speaker's)father",
"お母さん - おかあさん - mother",
"母 - はは - (speaker's)mother",
"姉 - あね - older sister",
"お姉さん - おねえさん - older sister",
"妹 - いもうと - younger sister",
"おなか - stomach",
"兄 - あに - older brother",
"お兄さん - おにいさん - older brother",
"弟 - おとうと - younger brother",
"若い - わかい - young",
"結婚 - けっこん - marriage",
"自転車 - じてんしゃ - bicycle",
"自分 - じぶん - self, oneself",
"答える - こたえる - answer, reply",
"病気 - びょうき - illness",
"死ぬ - しぬ - die",
"痛い - いたい - painful",
"つける - switch on",
"飛ぶ - とぶ - fly",
"飛行機 - ひこうき - airplane",
"頭 - あたま - head",
"顔 - かお - face",
"あれ - that over there",
"お手洗い - おてあらい - toilet, bathroom",
"冷たい - つめたい - cold (things, touch)",
"汚い - きたない - dirty",
"太い - ふとい - thick, fat",
"曇る - くもる - become cloudy",
"まずい - bad-tasting, bad",
"置く - おく - put, leave",
"辺 - へん - vicinity, part",
"黄色い - きいろい - yellow",
"易しい - やさしい - easy, simple",
"留学生 - りゅうがくせい - student studying abroad",
"そば - side, vicinity",
"起きる - おきる - get up, get out of bed",
"起きる - おきる - occur",
"寝る - ねる - sleep, go to sleep",
"細い - ほそい - thin, slender, narrow",
"締める - しめる - tighten, fasten",
"甘い - あまい - sweet",
"辛い - からい - spicy, salty",
"言葉 - ことば - word, language",
"呼ぶ - よぶ - call, name",
"片仮名 - かたかな - katakana",
"平仮名 - ひらがな - hiragana",
"授業 - じゅぎょう - class, lesson",
"あそこ - over there",
"狭い - せまい - narrow, restricted",
"嫌い - きらい - dislike",
"鼻 - はな - nose",
"おいしい - tasty",
"大丈夫 - だいじょうぶ - alright, OK",
"なる - become",
"七 - しち - seven",
"木 - き - tree, wood",
"何 - なん - what, which",
"先月 - せんげつ - last month",
"やる - give (to an inferior)",
"先週 - せんしゅう - last week",
"来月 - らいげつ - next month",
"来週 - らいしゅう - next week",
"中 - なか - inside, middle",
"もう - another, again",
"よく - well",
"二人 - ふたり - two persons",
"テレビ - television",
"外 - そと - outside, open air",
"休み - やすみ - rest, holiday, absence",
"出口 - でぐち - exit, exit ramp",
"下手 - へた - not good at",
"山 - やま - mountain",
"川 - かわ - river, stream",
"空 - そら - sky, weather",
"あまり - (not) much",
"海 - うみ - sea, ocean",
"毎日 - まいにち - every day",
"毎年 - まいとし - every year",
"毎年 - まいねん - every year",
"毎週 - まいしゅう - every week",
"毎月 - まいつき - every month",
"花 - はな - flower",
"女の子 - おんなのこ - girl, daughter",
"男の子 - おとこのこ - boy, baby boy",
"家 - いえ - house, home",
"家内 - かない - my wife",
"ホテル - hotel",
"雨 - あめ - rain",
"雪 - ゆき - snow, snowfall",
"青い - あおい - blue",
"暗い - くらい - dark, dreary, shadowy",
"東 - ひがし - east, eastern",
"西 - にし - west, western",
"南 - みなみ - south",
"北 - きた - north",
"向こう - むこう - the other side, the other party, opponent",
"開く - あく - open",
"もちろん - of course, no doubt",
"初めて - はじめて - for the first time",
"スポーツ - sport",
"半分 - はんぶん - half",
"毎朝 - まいあさ - every morning",
"今朝 - けさ - this morning",
"毎晩 - まいばん - every evening",
"夕方 - ゆうがた - evening",
"ニュース - news",
"話 - はなし - talk, story",
"英語 - えいご - English",
"会社 - かいしゃ - company, corporation",
"電話 - でんわ - telephone, phone call",
"電気 - でんき - electricity, electric light",
"バス - bus",
"車 - くるま - car",
"クラス - class",
"地図 - ちず - map, atlas",
"パーティー - party",
"止まる - とまる - come to a stop, cease",
"渡す - わたす - carry across, hand over",
"渡る - わたる - cross, ford, go across",
"アパート - apartment, flat, apartment house",
"レコード - record",
"外国 - がいこく - foreign country",
"カメラ - camera",
"外国人 - がいこくじん - foreigner",
"テープ - tape, cassette",
"黒い - くろい - black, dark",
"銀行 - ぎんこう - bank",
"地下鉄 - ちかてつ - subway",
"牛肉 - ぎゅうにく - beef",
"肉 - にく - flesh, meat",
"魚 - さかな - fish",
"野菜 - やさい - vegetable",
"八百屋 - やおや - vegetable store, greengrocer",
"お茶 - おちゃ - tea (polite)",
"テスト - test, exam",
"料理 - りょうり - cooking, handling",
"作文 - さくぶん - composition, essay",
"消える - きえる - be extinguished, disappear",
"ラジオ - radio",
"タクシー - taxi, cab",
"ゆっくり - slowly",
"階段 - かいだん - steps, flight of stairs",
"レストラン - restaurant",
"夏休み - なつやすみ - summer vacation",
"風 - かぜ - wind",
"新聞 - しんぶん - newspaper",
"フィルム - film",
"デパート - department store, department",
"ベッド - bed",
"コート - coat, jacket",
"郵便局 - ゆうびんきょく - post office",
"交番 - こうばん - police box",
"ノート - note book, laptop",
"番号 - ばんごう - number, serial number",
"台所 - だいどころ - kitchen",
"有名 - ゆうめい - famous",
"町 - まち - town, machi, city quarter",
"トイレ - toilet",
"朝御飯 - あさごはん - breakfast",
"買い物 - かいもの - shopping, purchase",
"荷物 - にもつ - baggage, load",
"物 - もの - thing, object",
"持つ - もつ - maintain, last long",
"生まれる - うまれる - be born, come into existence",
"プール - pool",
"生徒 - せいと - pupil, student",
"エレベーター - elevator",
"パン - bread",
"ズボン - trousers, pants",
"練習 - れんしゅう - practice, training",
"習う - ならう - learn, practice",
"グラム - gram",
"問題 - もんだい - problem, question",
"あなた - you",
"便利 - べんり - convenience, handiness",
"こちら - here, this way",
"返す - かえす - return, repay",
"借りる - かりる - borrow",
"ボタン - button",
"貸す - かす - lend, lease",
"コート - court",
"切手 - きって - postage stamp",
"大切 - たいせつ - important, valuable",
"切符 - きっぷ - ticket",
"ポケット - pocket",
"ネクタイ - tie, necktie",
"降りる - おりる - get off, land",
"降る - ふる - fall, come down",
"着く - つく - arrive, make contact, settle",
"上着 - うわぎ - coat, jacket",
"脱ぐ - ぬぐ - remove clothes, take off",
"ギター - guitar",
"セーター - sweater, pullover",
"動物 - どうぶつ	animal",
"シャツ - shirt",
"ナイフ - knife",
"手紙 - てがみ - letter",
"絵 - え - picture, painting, drawing",
"雑誌 - ざっし - magazine, journal",
"音楽 - おんがく - music",
"薬 - くすり - drug, remedy, chemical",
"歌 - うた - song",
"映画 - えいが - movie",
"写真 - しゃしん - photograph",
"スカート - skirt",
"角 - かど - corner, edge, angle",
"旅行 - りょこう - travel, trip",
"大使館 - たいしかん - embassy",
"映画館 - えいがかん - movie theater",
"宿題 - しゅくだい - homework",
"ゼロ - zero",
"洋服 - ようふく - clothes",
"教室 - きょうしつ - classroom, class",
"窓 - まど - window, windowpane",
"家族 - かぞく - family, household",
"二十歳 - はたち - 20 years old",
"兄弟 - きょうだい - sibling",
"果物 - くだもの - fruit",
"自動車 - じどうしゃ - automobile",
"頼む - たのむ - ask, request",
"並ぶ - ならぶ - line up, be parallel",
"並べる - ならべる - line up, display, set up",
"病院 - びょういん - hospital",
"医者 - いしゃ - doctor",
"歯 - は - tooth, cog",
"コップ - cup, glass",
"忙しい - いそがしい - busy, occupied",
"疲れる - つかれる - get tired, become fatigued",
"危ない - あぶない - dangerous, uncertain",
"意味 - いみ - meaning, significance",
"つまらない - boring, dull",
"マッチ - match, matchbox",
"公園 - こうえん - park, public garden",
"ストーブ - paraffin heater, stove",
"テープレコーダー - tape recorder, cassette recorder",
"登る - のぼる - climb, mount, go up",
"バター - バター	butter",
"辞書 - じしょ	dictionary",
"カレンダー - カレンダー - calendar",
"勤める - つとめる - serve, hold a job",
"ワイシャツ - ワイシャツ - (business) shirt, (white) shirt",
"池 - いけ - pond",
"泳ぐ - およぐ - swim",
"洗う - あらう - wash",
"ハンカチ - handkerchief",
"冷蔵庫 - れいぞうこ - refrigerator",
"涼しい - すずしい - cool, refreshing",
"スプーン - spoon",
"建物 - たてもの - building, structure",
"フォーク - fork",
"橋 - はし - bridge",
"隣 - となり - neighboring house, next seat",
"横 - よこ - side, width across",
"どうぞ - please",
"ボールペン - ballpoint pen",
"そちら - there, that way",
"そば - buckwheat noodles, soba",
"静か - しずか - quiet, tranquil",
"暇 - ひま - free time, spare time",
"両親 - りょうしん - parents",
"どなた - どなた - who",
"困る - こまる - be at a loss, in a jam, in trouble",
"塩 - しお - salt",
"砂糖 - さとう - sugar",
"薄い - うすい - thin, weak, pale",
"厚い - あつい - thick, bulky",
"スリッパ - slippers",
"奥さん - おくさん - married lady, your wife",
"皆さん - みなさん - everybody, ladies and gentlemen",
"誕生日 - たんじょうび - birthday",
"たくさん - in large quantity, plenty",
"あちら - way over there",
"庭 - にわ - garden, court",
"咲く - さく - bloom, blossom",
"吹く - ふく - blow, play on a wind instrument",
"散歩 - さんぽ - walk, stroll",
"葉書 - はがき - postcard",
"吸う - すう - inhale, suck",
"撮る - とる - photograph, shoot, film",
"再来年 - さらいねん - the year after next",
"鳥 - とり - bird, poultry",
"鳴く - なく - cry, chirp, meow",
"声 - こえ - voice, sound",
"卵 - たまご - egg",
"弾く - ひく - play on",
"丸い - まるい - round",
"嫌 - いや - dislike, have a dislike for",
"大勢 - おおぜい - large numbers, a lot of",
"机 - つくえ - desk, table",
"本棚 - ほんだな - bookshelf",
"洗濯 - せんたく - laundering, washing",
"喫茶店 - きっさてん - coffee shop, tea house, café",
"灰皿 - はいざら - ashtray",
"居る - いる - be present",
"戸 - と - door, shutter",
"豚肉 - ぶたにく - pork, hog meat",
"お菓子 - おかし - sweets, snacks",
"鉛筆 - えんぴつ - pencil",
"万年筆 - まんねんひつ - fountain pen",
"箱 - はこ - box, case",
"玄関 - げんかん - entrance, door",
"眼鏡 - めがね - glasses, judgment",
"封筒 - ふうとう - envelope",
"たばこ - tobacco, cigarette",
"掃除 - そうじ - cleaning",
"ちょうど - just, as if",
"ちょっと - just a moment, just a little, easily",
"帽子 - ぼうし - cap, hat",
"零 - れい - zero, naught",
"食堂 - しょくどう - dining hall, restaurant",
"丈夫 - じょうぶ - healthy, stout",
"傘 - かさ - umbrella, parasol",
"靴 - くつ - shoes, boots",
"靴下 - くつした - socks, stockings",
"磨く - みがく - polish, grind",
"いつも - always, usually",
"クラス - class, lesson",
"大人 - おとな - adult",
"私 - わたくし - I, myself",
"元気 - げんき - vigor, spirits",
"門 - もん - gate, entrance",
"かかる - catch, get",
"ああ - that kind of",
"字引 - じびき - dictionary",
"さす - pour",
"どうも - for some reason, somehow",
"結構 - けっこう - all right, no thank you",
"結構 - けっこう - quite",
"一緒 - いっしょ - together",
"辛い - からい - strict, severe",
"まずい - bad, no good",
"背広 - せびろ - business suit",
"まずい - problematic, troublesome",
"花瓶 - かびん - flower vase"]

number_of = 15
selected_words = pick_words(jp, number_of)

if selected_words is not None:
    print("Selected Words:")
    for words in selected_words:
        print(words)

